```{r}
library(readr)
library(gmodels)
library(MASS)
library(dplyr)

```

```{r}
virus <- read_csv("virus_modified3.csv")

virus = virus %>% select(2:ncol(.))
virus[is.na(virus)] <- 0


virus$is_coinf = factor(virus$is_coinf , ordered=TRUE)
levels(virus$is_coinf)

library(ordinal)

Model = clm(is_coinf ~ ContactDiar_1+Pond+KeepAnimal+KillingAnimal +EatCookRawMeat+Gender+ Age + `Year of enrollment_2013`+`Year of enrollment_2015`+Well+Tap, data=virus)

summary(Model)


#The variance is almost equal to the mean
mean(virus$is_coinf)
var(virus$is_coinf)
```

```{r}

virus <- as.data.frame(unclass(virus))
str(virus)


virus[,'is_coinf']<-factor(virus[,'is_coinf'])

str(virus)

polr <- polr(is_coinf ~ ContactDiar_1+Pond+KeepAnimal+KillingAnimal +EatCookRawMeat+Gender+ Age + `Year of enrollment_2013`+`Year of enrollment_2015`+Well+Tap, data=virus)
summary(polr)

ctable <- coef(summary(polr))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) *2
ctable <- cbind(ctable, "p value" = p)

polr_2 <- stepAIC(polr)
summary(polr_2)

ctable <- coef(summary(polr_2))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) *2
ctable <- cbind(ctable, "p value" = p)

```


```{r}
require(pscl)
m1 <- zeroinfl(formula = is_coinf ~ .-is_coinf-Gender  | Gender ,
          data=virus )
summary(m1)


m1 <- glm(formula = is_coinf ~ `ProvincialCity_Thanh Binh`+Age +`CentrallyCity_Khanh Hoa` +SiteRecruitment_2 +SiteRecruitment_5 , family=poisson(link=log),
          data=virus )
summary(m1)

m1 <- glm(formula = is_coinf ~ContactDiar_1+Pond+KeepAnimal+KillingAnimal +EatCookRawMeat+Gender+ Age + `Year of enrollment_2013`+`Year of enrollment_2015`+Well+Tap, family=poisson(link=log),
          data=virus )
summary(m1)


nbGLM <- glm.nb(is_coinf ~ContactDiar_1+Pond+KeepAnimal+KillingAnimal +EatCookRawMeat+Gender+ Age + `Year of enrollment_2013`+`Year of enrollment_2015`+Well+Tap, data=virus)
summary(nbGLM)

library(pscl)
vuong(m1, nbGLM )

library("nnet")
test <- multinom(is_coinf ~ContactDiar_1+Pond+KeepAnimal+KillingAnimal +EatCookRawMeat+Gender+ Age + `Year of enrollment_2013`+`Year of enrollment_2015`+Well+Tap, data = virus)
summary(test)
z <- summary(test)$coefficients/summary(test)$standard.errors
p <- (1 - pnorm(abs(z), 0, 1))*2
```


```{r}
library(nnet)
virus2 <- read_csv("virus_modified5.csv")
str(virus2)
is_coinf = virus2$is_coinf

logit_1 <- glm(virus2$NumberDiarEpi~is_coinf, family = poisson(link=log),data = virus2)
summary(logit_1)

logit_1 <-glm(virus2$MucoidStool ~is_coinf, family = "binomial", data = virus2)
summary(logit_1)
z <- summary(logit_1)$coefficients/summary(logit_1)$standard.errors
p <- (1 - pnorm(abs(z), 0, 1)) * 2
```


```{r}
library(nnet)
virus2 <- read_csv("virus_modified6.csv")

is_coinf = virus2$is_coinf

logit_1 <- glm(NumberDiarEpi ~Sapovirus, family = poisson(link=log),data = virus2)
summary(logit_1)

logit_1 <- glm(`Length of stay` ~Sapovirus, family = poisson(link=log),data = virus2)
summary(logit_1)

logit_1 <-glm(ThreeDaysFever~Sapovirus, family = "binomial", data = virus2)
summary(logit_1)
```


```{r}
library(tidyverse)
library(rstatix)

virus2 <- read_csv("virus_modified5.csv")


virus2 <- virus2 %>% select(contains(c("virus_",'NumberDiarEpi')))
#virus2 <- virus2 %>% select(- KnownTemp )

str(virus2)
#Temp = virus2$Temp
#KnownTemp = virus2$KnownTemp
#BloodStool = virus2$BloodStool 
#MucoidStool  =virus2$MucoidStoo
#AbdominalPain = virus2$AbdominalPain
ThreeDaysFever= virus2$ThreeDaysFever

logit_1 <-glm(Temp~.-Temp, family = "binomial", data = virus2)
summary(logit_1)

logit_1 <- glm(NumberDiarEpi~.-NumberDiarEpi, family = poisson(link=log),data = virus2)
summary(logit_1)

```


